### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by daofeng2015** [openwrt-develop/luci-app-koolproxy#1]
![qq 20170401134101](https://cloud.githubusercontent.com/assets/14891398/24575736/fe4d6096-16e0-11e7-9705-95cc814d9601.png)能改成直接下载到/usr/share/koolproxy/date/目录里面不行吗？
或者做软链接也可以啊

**Comment by panda-mute** [comment]
你这是那个目录，一直放在/usr/share/koolproxy/data/下的啊

**Comment by daofeng2015** [comment]
默认的就是根目录,要下载到别的地方
