### ISSUE TITLE
https过滤

### ISSUE THREAD

**Issue by wclmgcd** [openwrt-develop/luci-app-koolproxy#12]
我开启全局http+https,没有安装证书,YouTube,Google,打不开显示的是:你的链接不是私密链接,但谷歌的二级域名如mail.google.com等没有问题,推特,Facebook也没有问题.   不用代理的v2ex也是显示你的链接不是私密链接,但淘宝,京东,百度之类的https没有问题.这个是https://github.com/shadowsocks/luci-app-shadowsocks/issues/139我的设置有问题,还是koolproxy本身的问题?如果是,是否可以加入白名单功能,把YouTube,Google加入

我另一个路由K2用的官方修改版,就不会出现这个问题

**Comment by wclmgcd** [comment]
@@||无效

**Comment by panda-mute** [comment]
你的官改版估计是方案1
https://github.com/openwrt-develop/luci-app-koolproxy/blob/master/koolproxy.txt
你自己看看吧，可以用老版本

**Comment by wclmgcd** [comment]
不是，因为草榴可以过滤
