### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by w01230** [openwrt-develop/luci-app-koolproxy#13]
I try to compile this package by myself on openwrt(lede) truck. And after compiling the elf file koolproxy can not run. Because after compiling the elf is smaller than the original size, it seems the elf file koolproxy is damaged.  I need to copy the original elf file to openwrt via ssh and it works well.

Platform: mips  Compile: debian and ubuntu.

**Comment by panda-mute** [comment]
@w01230 
Should be fixed in new version
086b1be164903462eb835cbe6e59ff4212e081eb

**Comment by w01230** [comment]
close it. It seems fixed.
