### ISSUE TITLE
LEDE trunk存在bug

### ISSUE THREAD

**Issue by juyyao** [openwrt-develop/luci-app-koolproxy#14]
在最新版的LEDE TRUNK中无法保存应用修改

**Comment by panda-mute** [comment]
暂时不要用trunk版本

**Comment by panda-mute** [comment]
@juyyao 
Please test with the latest fix: fa57080b5d805d4e614193824f89a8ac1fe05836

**Comment by juyyao** [comment]
fix无效....还是无法保存应用,另外log也不行,点更新规则无法显示log

**Comment by panda-mute** [comment]
trunk版本的luci更改了work flow，多少现在都有些问题，等稳定了再去fix，当然你有精力欢迎PR

**Comment by panda-mute** [comment]
@juyyao 最新版已解决
