### ISSUE TITLE
勾选自定义规则后无法启动，导致没网

### ISSUE THREAD

**Issue by liwenjie119** [openwrt-develop/luci-app-koolproxy#18]
规则订阅增加了https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt
然后勾选的自定义规则，就无法启动，去掉勾选就能正常使用

**Comment by liwenjie119** [comment]
目前发现的问题是勾选自定义并添加第三方规则后，会在user.txt内复制两份。另外，科学上网后的广告无法过滤。
可以参考 https://github.com/user1121114685/koolproxyR 把本项目完善一下

**Comment by panda-mute** [comment]
不明白复制两份是什么意思。科学上网的问题需要固件配合，不能理解的话，自己看koolproxy.txt。
