### ISSUE TITLE
koolproxy停止更新了，大佬可用https://github.com/user1121114685/koolproxyR.git作为源修改一下？

### ISSUE THREAD

**Issue by shenzt68** [openwrt-develop/luci-app-koolproxy#19]
koolproxy停止更新了，大佬可用https://github.com/user1121114685/koolproxyR.git作为源修改一下？

**Comment by panda-mute** [comment]
修改什么呢？如果是规则，自己添加过来1不就完了

**Comment by shenzt68** [comment]
![image](https://user-images.githubusercontent.com/17406910/57011615-21f0b380-6c35-11e9-89d1-42aad92e281c.png)
规则已经不能更新。
自己怎么订阅规则？

**Comment by panda-mute** [comment]
自己拖到页面底部弄吧
