### ISSUE TITLE
更新报udhcpc: no lease, failing

### ISSUE THREAD

**Issue by nu1ee** [openwrt-develop/luci-app-koolproxy#3]
Fri Apr  7 09:58:09 HKT 2017: 正在下载adblockplus规则...
Fri Apr  7 09:59:58 HKT 2017: 检测到adblockplus规则有更新，开始转换规则！
Fri Apr  7 09:59:58 HKT 2017: adblockplus规则转换完成，应用新规则。
udhcpc: started, v1.25.1
udhcpc: sending discover
udhcpc: no lease, failing

这有影响的吗？

**Comment by panda-mute** [comment]
这是dnsmasq重启的输出，和koolproxy无关，不影响使用
