### ISSUE TITLE
依赖缺失

### ISSUE THREAD

**Issue by daofeng2015** [openwrt-develop/luci-app-koolproxy#4]
处理规则列表缺少diffutils

**Comment by panda-mute** [comment]
个人偏向使用busybox中的diff，所以不会改为diffutils。
有需要的话自己改Makefile吧。

**Comment by November-raining** [comment]
默认makefile编译，
看了下自己编译固件的.config文件busybox中没有配置diff，但编译了diffutils到固件
实际ipk安装使用似乎没问题，所以针对这个issue有必要进行改动么

**Comment by panda-mute** [comment]
只要有diff就行，没有影响
