### ISSUE TITLE
my router wndr4300 will reboot if I click the service---koolproxy in luci web on lede 17.01

### ISSUE THREAD

**Issue by jack338c** [openwrt-develop/luci-app-koolproxy#9]
before is ok.
after I recompile the newest luci-app-koolproxy then the issuse occur

thank you for bring this awesome stuff to our planet

**Comment by panda-mute** [comment]
Which version working for you? You can track the change.

**Comment by jack338c** [comment]
Sorry,forgot to attach
Kernel Version | 4.4.79
LEDE Reboot 17.01-SNAPSHOT r3484-66b071f

thanks
